import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, cp, symlink, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { parseMarkdown } from "@nuxtjs/mdc/runtime";
import { channel, hash, makeMessage, makePublication, readPosts } from "./content.mjs";
import { openGitState, validateState } from "./state.mjs";
import { publishPost, resolvePending, telegramRequest, waitForPage } from "./publisher.mjs";

async function post(markdown = "Текст **заметки**.", telegram = { publish: true, mode: "full" }) {
  const parsed = await parseMarkdown(markdown, { highlight: false });
  return { ...parsed, data: { ...parsed.data, title: "Заметка 👋" }, slug: "2026-09-10-example", url: "https://example.com/blog/2026-09-10-example", telegram };
}

function memoryStore() {
  let durable = { version: 1, channel, posts: {} };
  return {
    state: structuredClone(durable),
    async save(next) { durable = structuredClone(validateState(next)); },
    reload() { this.state = structuredClone(durable); return this; },
  };
}

test("Markdown preserves Cyrillic, emoji offsets, links, code, lists and image URLs", async () => {
  const payload = await makeMessage(await post("👋 **жирный & <текст>** [ссылка](/about)\n\n`x < y`\n\n```js\nconst x = 1;\n```\n\n1. Один\n2. Два\n\n![Фото](/photo.png)"));
  const bold = payload.entities.find((e) => e.type === "bold" && e.offset > 0);
  assert.equal(payload.text.slice(bold.offset, bold.offset + bold.length), "жирный & <текст>");
  assert.ok(payload.entities.some((e) => e.url === "https://example.com/about"));
  assert.ok(payload.entities.some((e) => e.url === "https://example.com/photo.png"));
  assert.ok(payload.entities.some((e) => e.type === "pre" && e.language === "js"));
  assert.ok(payload.entities.some((e) => e.type === "code"));
  assert.match(payload.text, /1\. Один\n2\. Два/);
  assert.match(payload.text, /Читать в блоге: https:/);
  for (const entity of payload.entities) assert.ok(entity.offset + entity.length <= payload.text.length);
});

test("teaser replaces long body; oversized full text and unsupported tables fail before sending", async () => {
  const full = await post("а".repeat(4100));
  await assert.rejects(makeMessage(full), /4096/);
  full.telegram = { publish: true, mode: "teaser", text: "Коротко о **главном**." };
  assert.match((await makeMessage(full)).text, /Коротко о главном/);
  const table = await post("| A | B |\n|---|---|\n| 1 | 2 |");
  await assert.rejects(makeMessage(table), /teaser/);
});

test("discovery excludes English files and opt-in typos fail explicitly", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "me-telegram-content-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, "content/en"), { recursive: true });
  await mkdir(join(root, "public"));
  await writeFile(join(root, "public/CNAME"), "example.com\n");
  await writeFile(join(root, "content/en/en-only.md"), "English");
  await writeFile(join(root, "content/plain.md"), "---\ntitle: Blog only\n---\nText");
  assert.equal((await readPosts(root)).length, 1);
  assert.equal((await readPosts(root))[0].telegram, undefined);
  await writeFile(join(root, "content/plain.md"), '---\ntitle: Bad\ntelegram:\n  publish: "true"\n  mode: full\n---\nText');
  await assert.rejects(readPosts(root), /publish/);
});

test("page polling requires exact generated bytes; an old 200 page is insufficient", async () => {
  let calls = 0, sleeps = 0;
  const p = await post();
  await waitForPage(p, hash("new html"), {
    fetcher: async () => new Response(++calls === 1 ? "old html" : "new html"),
    sleep: async () => { sleeps++; }, attempts: 2,
  });
  assert.equal(calls, 2);
  assert.equal(sleeps, 1);
  await assert.rejects(waitForPage(p, hash("new html"), {
    fetcher: async () => new Response("old html"), attempts: 1,
  }), /не отправлен/);
});

test("durable reservation precedes send; reruns and ordinary edits do not repost", async () => {
  const store = memoryStore();
  const p = await post();
  let calls = 0;
  const options = {
    post: p, store, token: "test", wait: async () => {},
    request: async () => {
      calls++;
      assert.equal(store.reload().state.posts[p.slug].status, "pending");
      return { message_id: 123 };
    },
  };
  await publishPost(options);
  p.data.title = "Исправленный заголовок";
  assert.equal(await publishPost(options), "already published");
  assert.equal(calls, 1);
  assert.equal(store.reload().state.posts[p.slug].messageId, 123);
});

test("existing message_id is never sent again; update targets it only explicitly", async () => {
  const p = await post("Text", { publish: true, mode: "full", message_id: 34 });
  const store = memoryStore();
  const options = {
    post: p, store, token: "test", wait: async () => {},
    request: async (method, payload) => {
      assert.equal(method, "editMessageText");
      assert.equal(payload.message_id, 34);
      return { message_id: 34 };
    },
  };
  assert.equal(await publishPost(options), "already published");
  assert.equal(await publishPost({ ...options, update: true }), "updated: 34");
  assert.equal(await publishPost({ ...options, update: true }), "unchanged");
});

test("failed durable reservation or unavailable page prevents a Telegram request", async () => {
  let calls = 0;
  const p = await post();
  const options = {
    post: p, token: "test", request: async () => { calls++; },
    store: { ...memoryStore(), save: async () => { throw new Error("push failed"); } }, wait: async () => {},
  };
  await assert.rejects(publishPost(options), /push failed/);
  await assert.rejects(publishPost({ ...options, store: memoryStore(), wait: async () => { throw new Error("not live"); } }), /not live/);
  assert.equal(calls, 0);
});

test("ambiguous network failure blocks retries until manual reconciliation", async () => {
  const store = memoryStore();
  const p = await post();
  let calls = 0;
  const options = {
    post: p, store, token: "test", wait: async () => {},
    request: async () => { calls++; throw new Error("timeout"); },
  };
  await assert.rejects(publishPost(options), /timeout/);
  store.reload();
  await assert.rejects(publishPost(options), /незавершённая/);
  assert.equal(calls, 1);
  await resolvePending(store, p.slug, 321);
  assert.equal(await publishPost(options), "already published");
  assert.equal(store.reload().state.posts[p.slug].messageId, 321);
});

test("failed final journal push retains a remote pending record and reports the accepted ID", async () => {
  const store = memoryStore();
  const save = store.save.bind(store);
  let saves = 0;
  store.save = async (state) => { if (++saves === 2) throw new Error("offline"); await save(state); };
  const p = await post();
  await assert.rejects(publishPost({ post: p, store, token: "test", wait: async () => {}, request: async () => ({ message_id: 99 }) }), /resolve --message-id 99/);
  assert.equal(store.reload().state.posts[p.slug].status, "pending");
  await resolvePending(store, p.slug, 99);
  assert.equal(store.reload().state.posts[p.slug].messageId, 99);
});

test("definitive rejection releases reservation; --not-sent restores pre-edit state", async () => {
  const store = memoryStore();
  const p = await post();
  const options = { post: p, store, token: "test", wait: async () => {}, request: async () => { throw Object.assign(new Error("rejected"), { rejected: true }); } };
  await assert.rejects(publishPost(options), /rejected/);
  assert.equal(store.reload().state.posts[p.slug], undefined);
  p.telegram.message_id = 34;
  await assert.rejects(publishPost({ ...options, update: true, request: async () => { throw new Error("timeout"); } }), /timeout/);
  await resolvePending(store, p.slug);
  assert.equal(store.reload().state.posts[p.slug].messageId, 34);
});

test("API handles rejection, ambiguous errors, and unchanged edits without exposing token", async () => {
  const json = (value, status = 200) => new Response(JSON.stringify(value), { status });
  await assert.rejects(telegramRequest("sendMessage", {}, "secret", async () => json({ ok: false, error_code: 403 }, 403)), (e) => e.rejected === true);
  await assert.rejects(telegramRequest("sendMessage", {}, "secret", async () => { throw new Error("https://api.telegram.org/botsecret/sendMessage"); }), (e) => !e.message.includes("secret") && !e.rejected);
  await assert.rejects(telegramRequest("sendMessage", {}, "secret", async () => json({ ok: false, error_code: 500 }, 500)), (e) => !e.rejected);
  assert.equal((await telegramRequest("editMessageText", { message_id: 34 }, "secret", async () => json({ ok: false, error_code: 400, description: "Bad Request: message is not modified" }, 400))).message_id, 34);
});

test("Git journal persists in an isolated branch and rejects concurrent stale writers", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "me-telegram-git-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const git = (cwd, ...args) => execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
  git(root, "init", "--bare", "remote.git");
  for (const name of ["a", "b"]) {
    git(root, "init", name);
    git(join(root, name), "remote", "add", "origin", join(root, "remote.git"));
    await writeFile(join(root, name, "dirty.txt"), "keep me");
  }
  const a = openGitState(join(root, "a"));
  const b = openGitState(join(root, "b"));
  a.state.posts.example = { status: "pending", attemptId: "a" };
  b.state.posts.example = { status: "pending", attemptId: "b" };
  await a.save(a.state);
  await assert.rejects(b.save(b.state), /Git push/);
  const fresh = openGitState(join(root, "b"));
  assert.equal(fresh.state.posts.example.attemptId, "a");
  fresh.state.posts.example = { status: "sent", messageId: 123 };
  await fresh.save(fresh.state);
  await assert.rejects(a.save(a.state), /Git push/);
  assert.equal(openGitState(join(root, "a")).state.posts.example.messageId, 123);
  assert.equal(git(join(root, "a"), "status", "--short"), "?? dirty.txt");
  assert.equal(git(join(root, "remote.git"), "ls-tree", "--name-only", "telegram-state"), "state.json");
});

test("CLI preview, prepare and existing-post import work together without a token or Telegram calls", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "me-telegram-cli-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const repo = join(root, "repo");
  const sourceRoot = fileURLToPath(new URL("../../", import.meta.url));
  execFileSync("git", ["init", "--bare", join(root, "remote.git")], { stdio: "pipe" });
  execFileSync("git", ["init", repo], { stdio: "pipe" });
  execFileSync("git", ["remote", "add", "origin", join(root, "remote.git")], { cwd: repo });
  await cp(join(sourceRoot, "scripts"), join(repo, "scripts"), { recursive: true });
  await symlink(join(sourceRoot, "node_modules"), join(repo, "node_modules"));
  await mkdir(join(repo, "content/en"), { recursive: true });
  await mkdir(join(repo, "public"));
  await writeFile(join(repo, "public/CNAME"), "example.com\n");
  const source = '---\ntitle: Existing post\ndate: 2026-09-10\ntelegram:\n  publish: true\n  mode: full\n  message_id: 34\n---\nHello **world**.';
  await writeFile(join(repo, "content/example.md"), source);
  await writeFile(join(repo, "content/en/example.md"), "English");
  await mkdir(join(repo, ".output/public/blog/example"), { recursive: true });
  await writeFile(join(repo, ".output/public/blog/example/index.html"), "<article>Synthetic generated page</article>");
  const cli = (...args) => execFileSync(process.execPath, ["scripts/telegram.mjs", ...args], {
    cwd: repo, encoding: "utf8", stdio: "pipe", env: { ...process.env, TELEGRAM_BOT_TOKEN: "" },
  });
  assert.match(cli("preview", "example"), /Hello world/);
  assert.match(cli("prepare"), /Подготовлено страниц: 1/);
  const manifest = JSON.parse(await readFile(join(repo, ".output/telegram-manifest.json"), "utf8"));
  assert.equal(manifest.posts.example.sourceHash, hash(source));
  assert.match(cli("publish"), /Повторной отправки нет/);
  assert.equal(JSON.parse(cli("status")).posts.example.messageId, 34);
  assert.match(cli("publish"), /Повторной отправки нет/);
  // A newly opted-in source absent from this build must not be sent.
  await writeFile(join(repo, "content/new-post.md"), source.replace("  message_id: 34\n", ""));
  assert.throws(() => cli("publish"), (error) => error.stderr.includes("Пересоберите сайт"));
  assert.equal(JSON.parse(cli("status")).posts["new-post"], undefined);
  assert.throws(() => cli("update", "../../outside"), (error) => error.stderr.includes("Нужен slug"));

  const photoSource = source.replace("  message_id: 34\n", "") + '\n\n![One](/assets/one.jpg)\n\n![Two](/assets/two.jpg)';
  await writeFile(join(repo, "content/new-post.md"), photoSource);
  await mkdir(join(repo, ".output/public/blog/new-post"), { recursive: true });
  await writeFile(join(repo, ".output/public/blog/new-post/index.html"), "<article>Photo post</article>");
  assert.match(cli("preview", "new-post"), /Альбом после текста \(2\)/);
  assert.throws(() => cli("prepare"), (error) => error.stderr.includes("one.jpg"));
  await mkdir(join(repo, ".output/public/assets"), { recursive: true });
  await writeFile(join(repo, ".output/public/assets/one.jpg"), "photo-one");
  await writeFile(join(repo, ".output/public/assets/two.jpg"), "photo-two");
  cli("prepare");
  const photoManifest = JSON.parse(await readFile(join(repo, ".output/telegram-manifest.json"), "utf8"));
  assert.deepEqual(photoManifest.posts["new-post"].photos, [
    { url: "https://example.com/assets/one.jpg", hash: hash("photo-one") },
    { url: "https://example.com/assets/two.jpg", hash: hash("photo-two") },
  ]);
  const journal = openGitState(repo);
  journal.state.posts["new-post"] = {
    status: "pending", operation: "media", previous: {
      status: "partial", messageId: 100, photos: photoManifest.posts["new-post"].photos.map((photo) => photo.url),
    },
  };
  await journal.save(journal.state);
  assert.match(cli("resolve", "new-post", "--message-ids", "101,102"), /журнал исправлен/);
  assert.deepEqual(JSON.parse(cli("status")).posts["new-post"].mediaMessageIds, [101, 102]);
});


test("publication extracts ordered unique photos, keeps formatting, and enforces album limits", async () => {
  const p = await post("Before **bold**.\n\n![First](/one.jpg)\n\n![Second](/two.png)\n\n![Repeated](/one.jpg)\n\nAfter.");
  const { message, photos } = await makePublication(p);
  assert.deepEqual(photos, ["https://example.com/one.jpg", "https://example.com/two.png"]);
  assert.doesNotMatch(message.text, /📷|First|Second|Repeated/);
  assert.match(message.text, /Before bold\.\n\nAfter\./);
  const bold = message.entities.find((e) => e.type === "bold" && e.offset > 0);
  assert.equal(message.text.slice(bold.offset, bold.offset + bold.length), "bold");
  const many = Array.from({ length: 11 }, (_, i) => `![Photo](/${i}.jpg)`).join("\n\n");
  assert.equal((await makePublication(await post("Text\n\n" + many.split("\n\n").slice(0, 10).join("\n\n")))).photos.length, 10);
  await assert.rejects(makePublication(await post(many)), /максимум 10/);
  await assert.rejects(makePublication(await post("Text\n\n![Photo](file:///secret.jpg)")), /HTTP/);
  p.telegram = { publish: true, mode: "teaser", text: "Short.\n\n![Teaser](/teaser.jpg)" };
  assert.deepEqual((await makePublication(p)).photos, ["https://example.com/teaser.jpg"]);
});

test("album follows text with durable reservations, retains all IDs, and never reposts on rerun or update", async () => {
  const p = await post("Text\n\n![One](/one.jpg)\n\n![Two](/two.jpg)");
  const store = memoryStore();
  const calls = [];
  const options = { post: p, store, token: "test", wait: async () => {}, request: async (method, payload) => {
    calls.push(method);
    assert.equal(store.reload().state.posts[p.slug].status, "pending");
    if (method === "sendMediaGroup") {
      assert.equal(payload.reply_parameters.message_id, 100);
      assert.deepEqual(payload.media, [
        { type: "photo", media: "https://example.com/one.jpg" },
        { type: "photo", media: "https://example.com/two.jpg" },
      ]);
      assert.equal(store.state.posts[p.slug].previous.status, "partial");
      return [{ message_id: 101 }, { message_id: 102 }];
    }
    assert.doesNotMatch(payload.text, /📷/);
    return { message_id: 100 };
  } };
  await publishPost(options);
  assert.deepEqual(calls, ["sendMessage", "sendMediaGroup"]);
  assert.deepEqual(store.reload().state.posts[p.slug].mediaMessageIds, [101, 102]);
  assert.equal(await publishPost(options), "already published");
  p.data.title = "Changed title";
  await publishPost({ ...options, update: true });
  assert.deepEqual(calls, ["sendMessage", "sendMediaGroup", "editMessageText"]);
  assert.deepEqual(store.reload().state.posts[p.slug].mediaMessageIds, [101, 102]);
});

test("single photo rejection resumes only the photo and rejects changed partial publications", async () => {
  const p = await post("Text\n\n![One](/one.jpg)");
  const store = memoryStore();
  const calls = [];
  let reject = true;
  const options = { post: p, store, token: "test", wait: async () => {}, request: async (method, payload) => {
    calls.push(method);
    if (method === "sendPhoto") {
      assert.equal(payload.photo, "https://example.com/one.jpg");
      if (reject) throw Object.assign(new Error("rejected"), { rejected: true });
    }
    return { message_id: method === "sendMessage" ? 100 : 101 };
  } };
  await assert.rejects(publishPost(options), /rejected/);
  assert.equal(store.reload().state.posts[p.slug].status, "partial");
  p.data.title = "Changed";
  await assert.rejects(publishPost(options), /изменилась/);
  p.data.title = "Заметка 👋";
  reject = false;
  await publishPost(options);
  assert.deepEqual(calls, ["sendMessage", "sendPhoto", "sendPhoto"]);
  assert.deepEqual(store.reload().state.posts[p.slug].mediaMessageIds, [101]);
});

test("ambiguous album result blocks retries; reconciliation requires every photo ID", async () => {
  const p = await post("Text\n\n![One](/one.jpg)\n\n![Two](/two.jpg)");
  const store = memoryStore();
  let calls = 0;
  const options = { post: p, store, token: "test", wait: async () => {}, request: async (method) => {
    calls++;
    if (method === "sendMessage") return { message_id: 100 };
    throw new Error("timeout");
  } };
  await assert.rejects(publishPost(options), /timeout/);
  store.reload();
  await assert.rejects(publishPost(options), /незавершённая/);
  await assert.rejects(resolvePending(store, p.slug, 101), /все ID/);
  await assert.rejects(resolvePending(store, p.slug, [101]), /все ID/);
  await assert.rejects(resolvePending(store, p.slug, [101, 101]), /все ID/);
  await resolvePending(store, p.slug, [101, 102]);
  assert.equal(await publishPost(options), "already published");
  assert.equal(calls, 2);
  assert.equal(store.reload().state.posts[p.slug].messageId, 100);
});

test("media --not-sent restores partial state and text reconciliation retains planned photos", async () => {
  const p = await post("Text\n\n![One](/one.jpg)");
  const store = memoryStore();
  const options = { post: p, store, token: "test", wait: async () => {}, request: async () => { throw new Error("timeout"); } };
  await assert.rejects(publishPost(options), /timeout/);
  await resolvePending(store, p.slug, 100);
  assert.equal(store.reload().state.posts[p.slug].status, "partial");
  await assert.rejects(publishPost(options), /timeout/);
  await resolvePending(store, p.slug);
  assert.equal(store.reload().state.posts[p.slug].status, "partial");
  await publishPost({ ...options, request: async (method) => {
    assert.equal(method, "sendPhoto"); return { message_id: 101 };
  } });
  assert.equal(store.reload().state.posts[p.slug].status, "sent");
});

test("failed album journal writes never repeat text or automatically repeat uncertain media", async () => {
  const p = await post("Text\n\n![One](/one.jpg)");
  for (const failAt of [2, 3, 4]) {
    const store = memoryStore();
    const save = store.save.bind(store);
    let saves = 0;
    store.save = async (state) => { if (++saves === failAt) throw new Error("offline"); await save(state); };
    const calls = [];
    const options = { post: p, store, token: "test", wait: async () => {}, request: async (method) => {
      calls.push(method); return { message_id: method === "sendMessage" ? 100 : 101 };
    } };
    await assert.rejects(publishPost(options), failAt === 2 ? /message-id 100/ : failAt === 4 ? /message-ids 101/ : /offline/);
    const entry = store.reload().state.posts[p.slug];
    if (failAt === 2) await resolvePending(store, p.slug, 100);
    if (failAt === 4) {
      assert.equal(entry.operation, "media");
      await assert.rejects(publishPost(options), /незавершённая/);
      await resolvePending(store, p.slug, [101]);
    }
    await publishPost(options);
    assert.deepEqual(calls, ["sendMessage", "sendPhoto"]);
  }
});

test("API validates album arrays, missing IDs and incomplete responses", async () => {
  const payload = { media: [{ type: "photo", media: "https://example.com/one.jpg" }, { type: "photo", media: "https://example.com/two.jpg" }] };
  const reply = (result) => async () => new Response(JSON.stringify({ ok: true, result }));
  const messages = [{ message_id: 101 }, { message_id: 102 }];
  assert.deepEqual(await telegramRequest("sendMediaGroup", payload, "secret", reply(messages)), messages);
  for (const bad of [null, messages[0], [messages[0]], [{ message_id: 101 }, {}], [messages[0], messages[0]]]) {
    await assert.rejects(telegramRequest("sendMediaGroup", payload, "secret", reply(bad)), /сверка/);
  }
});
