// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16.03.2026, 17:59:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/crews/projects/me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/plugins/**/*.{js,ts,mjs}","/home/crews/projects/me/composables/**/*.{js,ts,mjs}","/home/crews/projects/me/utils/**/*.{js,ts,mjs}","/home/crews/projects/me/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/crews/projects/me/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;